---
- name: Get Server Uptime
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run uptime command
      shell: uptime
      register: uptime_result

    - name: Show uptime
      debug:
        msg: "{{ uptime_result.stdout }}"
