---
- name: Get Server Uptime
  hosts: all
  gather_facts: no
  tasks:
    - name: Run uptime command
      command: /usr/bin/uptime
      register: uptime_result

    - name: Show uptime
      debug:
        msg: "{{ uptime_result.stdout }}"
