---
- name: Basic Information
  hosts: localhost
  gather_facts: no   # We'll run commands manually

  tasks:
    - name: Get server date and time
      ansible.builtin.command: date
      register: server_date

    - name: Show server date and time
      ansible.builtin.debug:
        msg: "Server Date & Time: {{ server_date.stdout }}"
      
    - name: Create an empty file
      ansible.builtin.file:
        path: /home/{{ansible_user}}/file1.txt
        state: touch
        mode: '0644'
      
